### ISSUE TITLE
Checking for updates on launch crashes Robofont

### ISSUE THREAD

**Issue by arialcrime** [robofont-mechanic/mechanic-2#39]
When I agree to Mechanic’s “Check for Updates Now” when launching Robofont, it crashes Robofont.
System: macOS 12.0.1
Robofont: Version 4.2b (build 2112311655)

Here’s what the log is saying:
```
18/01/2022 16:13:08 >    ERROR > URLReader >> https://raw.githubusercontent.com/asaumierdemers/AddOverlap/master/AddOverlap.roboFontExt/info.plist already being fetched
18/01/2022 16:13:08 >    ERROR > URLReader >> https://raw.githubusercontent.com/adobe-type-tools/adjust-anchors-rf-ext/master/AdjustAnchors.roboFontExt/info.plist already being fetched
18/01/2022 16:13:08 >    ERROR > URLReader >> https://raw.githubusercontent.com/typemytype/arrangeWindowsRoboFontExtension/master/Arrange%20Windows.roboFontExt/info.plist already being fetched
18/01/2022 16:13:08 >    ERROR > URLReader >> https://raw.githubusercontent.com/typemytype/batchRoboFontExtension/master/Batch.roboFontExt/info.plist already being fetched
18/01/2022 16:13:08 >    ERROR > URLReader >> https://raw.githubusercontent.com/jenskutilek/Curve-Equalizer/master/RoboFont/Curve%20EQ.roboFontExt/info.plist already being fetched
18/01/2022 16:13:08 >    ERROR > URLReader >> https://raw.githubusercontent.com/typemytype/featurePreviewRoboFontExtension/master/FeaturePreview.roboFontExt/info.plist already being fetched
18/01/2022 16:13:08 >    ERROR > URLReader >> https://raw.githubusercontent.com/jenskutilek/RoboFont/master/Extensions/GlyphRotator.roboFontExt/info.plist already being fetched
18/01/2022 16:13:08 >    ERROR > URLReader >> https://raw.githubusercontent.com/luke-snider/GlyphWalker/master/GlyphWalker.roboFontExt/info.plist already being fetched
18/01/2022 16:13:08 >    ERROR > URLReader >> https://raw.githubusercontent.com/franzheidl/JetSetGlyphs/master/JetSetGlyphs.roboFontExt/info.plist already being fetched
18/01/2022 16:13:08 >    ERROR > URLReader >> https://raw.githubusercontent.com/adobe-type-tools/kernalytics-rf-ext/master/Kern-A-Lytics.roboFontExt/info.plist already being fetched
18/01/2022 16:13:08 >    ERROR > URLReader >> https://gitlab.com/typoman/robofont-mark-tool/raw/master/build/MarkPositioning.roboFontExt/info.plist already being fetched
18/01/2022 16:13:08 >    ERROR > URLReader >> https://raw.githubusercontent.com/typemytype/pathOperatorRoboFontExtension/master/PathOperator.roboFontExt/info.plist already being fetched
18/01/2022 16:13:08 >    ERROR > URLReader >> https://raw.githubusercontent.com/roboDocs/PenBallWizard/master/PenBallWizard.roboFontExt/info.plist already being fetched
18/01/2022 16:13:08 >    ERROR > URLReader >> https://raw.githubusercontent.com/jackjennings/Replicant/master/Replicant.roboFontExt/info.plist already being fetched
18/01/2022 16:13:08 >    ERROR > URLReader >> https://raw.githubusercontent.com/LettError/responsiveLettering/master/ResponsiveLettering.roboFontExt/info.plist already being fetched
18/01/2022 16:13:08 >    ERROR > URLReader >> https://raw.githubusercontent.com/mrecord/ScriptLauncher/master/ScriptLauncher.roboFontExt/info.plist already being fetched
18/01/2022 16:13:08 >    ERROR > URLReader >> https://gitlab.com/typoman/robofont-kerning-tool/raw/master/SimpleKerning.roboFontExt/info.plist already being fetched
18/01/2022 16:13:09 >    ERROR > Mechanic >> Cannot parse 'https://raw.githubusercontent.com/cjdunn/delorean/master/Delorean.roboFontExt/info.plist' for 'Delorean: Interpolation Preview'
18/01/2022 16:13:09 >    ERROR > Mechanic >> Invalid file
18/01/2022 16:13:09 >    ERROR > Mechanic >> Cannot parse 'https://raw.githubusercontent.com/cjdunn/delorean/master/Delorean.roboFontExt/info.plist' for 'Delorean: Interpolation Preview'
18/01/2022 16:13:09 >    ERROR > Mechanic >> Invalid file
18/01/2022 16:13:09 >    ERROR > Mechanic >> Cannot parse 'https://raw.githubusercontent.com/ninastoessinger/Touche/master/Touche.roboFontExt/info.plist' for 'Touché'
18/01/2022 16:13:09 >    ERROR > Mechanic >> maximum recursion depth exceeded while calling a Python object
18/01/2022 16:13:16 >   OUTPUT > ROBOFONT >> sure
18/01/2022 16:13:17 >   OUTPUT > ROBOFONT >> /Applications/Robofont4/RoboFont.app/Contents/Resources/lib/python37.zip/lib/scripting/extensionBundle.py:1055: UserWarning: Extension 'GlyphBrowser' short cut is not available: g - 1310720.
18/01/2022 16:13:18 >   OUTPUT > ROBOFONT >> /Applications/Robofont4/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/dialogs.py:55: DeprecationWarning: 'BaseMessageDiaglog.alloc().initWithMessageText_informativeText_alertStyle_buttonTitlesValues_window_resultCallback_' has been deprecated and will be removed.Please update your code.
18/01/2022 16:13:24 >    ERROR > Mechanic >> Cannot parse 'https://raw.githubusercontent.com/cjdunn/delorean/master/Delorean.roboFontExt/info.plist' for 'Delorean: Interpolation Preview'
18/01/2022 16:13:24 >    ERROR > Mechanic >> Invalid file
18/01/2022 16:13:25 >    ERROR > Mechanic >> Cannot parse 'https://raw.githubusercontent.com/cjdunn/delorean/master/Delorean.roboFontExt/info.plist' for 'Delorean: Interpolation Preview'
18/01/2022 16:13:25 >    ERROR > Mechanic >> Invalid file
18/01/2022 16:13:25 >    ERROR > Mechanic >> Cannot parse 'https://raw.githubusercontent.com/jenskutilek/RoboChrome/master/RoboChrome.roboFontExt/info.plist' for 'RoboChrome'
18/01/2022 16:13:25 >    ERROR > Mechanic >> maximum recursion depth exceeded while calling a Python object

```

Hope that helps!

**Comment by typemytype** [comment]
could you try a direct download and install?

https://github.com/robofont-mechanic/mechanic-2/archive/refs/heads/master.zip

I remember this has been fixed...

**Comment by arialcrime** [comment]
Oh yes, that solved it!

Thanks for the quick reply. 🦦

**Comment by arialcrime** [comment]
This is still happening to me when launching RF after waking up the computer from sleep. 
“Check for Updates Now” crashes RF and gives me this log:
```
28/06/2022 10:06:20 >    ERROR > Mechanic >> Cannot parse 'https://raw.githubusercontent.com/cjdunn/delorean/master/Delorean.roboFontExt/info.plist' for 'Delorean: Interpolation Preview'
28/06/2022 10:06:20 >    ERROR > Mechanic >> Invalid file
28/06/2022 10:06:21 >    ERROR > Mechanic >> Cannot parse 'https://raw.githubusercontent.com/cjdunn/delorean/master/Delorean.roboFontExt/info.plist' for 'Delorean: Interpolation Preview'
28/06/2022 10:06:21 >    ERROR > Mechanic >> Invalid file
28/06/2022 10:06:21 >    ERROR > Mechanic >> Cannot parse 'https://raw.githubusercontent.com/typemytype/tracerRoboFontExtension/master/Tracer.roboFontExt/info.plist' for 'Tracer'
28/06/2022 10:06:21 >    ERROR > Mechanic >> maximum recursion depth exceeded while calling a Python object

```
System: macOS 12.4
Robofont: Version 4.3b (build 2206031749)
Mechanic: 2.0

**Comment by typemytype** [comment]
mmm, a mega wild guess is that a failing internet connection is the cause... (or wifi which is not awake yet) 

cc @verbosus

**Comment by typemytype** [comment]
I guess I found the issue...

the async url loading will call the progress bar to update, but while the progress bar updates a async new call, the vanilla progress bar update needs to wait 0.0002 

could you test the latest commit?
